services:
  - type: web
    name: transcricao-reunioes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

